run:
  timeout: 5m
linters:
  enable:
    - dogsled
    - errorlint
    - gocritic
    - gocyclo
    - gofmt
    - gofumpt
    - gosec
    - makezero
    - misspell
    - nakedret
    - predeclared
    - revive
    - stylecheck
    - tagliatelle
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - wastedassign
    - whitespace
