name: CI
on:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - "README.md"
  pull_request:
    branches:
      - main
      - master
    paths-ignore:
      - "README.md"

permissions:
  contents: read

jobs:
  check:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go: ["1.20", "1.21"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup go ${{ matrix.go }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
          cache: false

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54
          args: --timeout=5m

      - name: Run govulncheck
        uses: golang/govulncheck-action@v1
        with:
          go-version-input: ${{ matrix.go }}
          go-package: ./...

      - name: Run tests
        run: |
          git diff --cached --exit-code
          go test -race -cover -v ./... -coverprofile=cover.out -covermode=atomic
          go test -bench . -benchmem
          go vet ./...

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./cover.out
